apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kea-postgres
  namespace: network-infra-ams23
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
  major: 18
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: kea
      owner: kea
