apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kea-postgres
  namespace: network-infra-ams23
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: 18
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: kea
      owner: kea
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kea-dhcpv4
  namespace: network-infra-ams23
spec:
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: kube-system/kea-macvlan-13
      labels:
        app: kea-dhcpv4
    spec:
      containers:
      - image: nginx:alpine
        command:
        - sleep
        - infinity
        name: idle
  replicas: 1
  selector:
    matchLabels:
      app: kea-dhcpv4
  strategy:
    type: Recreate
