apiVersion: v1
kind: Secret
metadata:
    name: pdns-secrets
    namespace: network-infra-ams23
data:
    PDNS_AUTH_API_KEY: ""
sops:
    age:
        - recipient: age13qg6tpdjfjxcucc9v0lprl2q8wfzvstamh6a6zhnmedq835f3ehsc56thu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbFhxenV1d29MczErZCtr
            c1BCOEZXRVdTNUk0TlExR0dCS2d0TWdxMUNjCnhUckJhbUVrSk93ZGlvZzRCZWM4
            bklPd1FYa2tvVmpjS3FRVFhoaWlPOHcKLS0tIDhObWtiYWFXSlQvcjR5eTA0ZldY
            U3hlazdyeEhKb3diUXZZTUtoRkZUWVUKgdxxGLr8WOntVe7qRcVkfGNsz5hCwBEO
            y46q/RngcdQyixmeZgPYeZGxtjz7G6voO+roVoCHn83odHNgbCaYuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f8vgexpv2fs0yhjes9tqn0rum4j7l0lxupxk66nn7jpa6cyh3etsqqd0ee
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeW84cVA1bkhqYXJjWjMy
            eHpVUnk0RHJJZEl6L0NyNFhZN204Ukg1MTBNCmthbkNXQjBNMUphRzFmdFJTOW1Q
            YzBTRlRoU3czcDFoMXNFME9XT3BaSXcKLS0tIEVrWWRSV2lmSVUyaU5wSzZKbjhv
            bHFLeFYxL01sZjJsUkI3OWY2SHE1UEkKBrDIF98SBvHcp6eOI4dcBlfgH3kMZzSm
            kr3VDFwvYekJ55tcH+zQdkvhWL24bYbngQeeiVVl8pKTPdZ2PHP8sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T08:18:04Z"
    mac: ENC[AES256_GCM,data:/nVaT/t/0QKscWSLtEEUYckGjAfGr3arvvlO+0YpaVAjdiG/VbR0ZrF2O4dPQPhQtm+UP9HgVrJ2+f2jBu9gaYCqT5rBdAux+QYjFwaz/jhNTKr/Vh4Kb2F50wRxL63oUfja9jKxjzk1mGLiKBj84m+YmJy96+r6/7lar6MxiKg=,iv:lzDm3RZlHGeFUE/LZQ6/rxReNF5OPCour9EiN56AX/k=,tag:X2VD2xyloCQgf22SYglJ3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
