apiVersion: v1
kind: Secret
metadata:
    name: pdns-secrets
    namespace: network-infra-ams23
data:
    PDNS_AUTH_API_KEY: ENC[AES256_GCM,data:8DWsDDf0JXZWddaJXGt00liUvGi40QM4U1ifxDH3CDd0K9lnHv19k898biKEuvDjKdtnBzy2p+E=,iv:jfXEeKwPj62f7h99N/EdFcuHAnHhgcdhios8XNFZMKA=,tag:1MyOX4jj0hYWETpgRurVYg==,type:str]
sops:
    age:
        - recipient: age13qg6tpdjfjxcucc9v0lprl2q8wfzvstamh6a6zhnmedq835f3ehsc56thu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMnUxM2lnd3BkUHVzQjBV
            VElvV2gwVTB6VzRocWNkbExodUJhNW9ZRXg4CkNtYkNoR2g3UHRCWDhlRU91dmlZ
            NEFtZjZyYUxTSkxKTG1oSmpBMEhObFkKLS0tIGpMK2hSemoyNGR6U1hkeGJwU09E
            MWpabStIbXpVRDl2K2lNcFlvYk00TjgKhSVyriUh7yiZLWFcYoMoX274xVf9j+dv
            a81JbaiZG6GKZdiLRaq7i7KPlGs2xKEu8My4dj4ZTVVOe8pJTTqO7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f8vgexpv2fs0yhjes9tqn0rum4j7l0lxupxk66nn7jpa6cyh3etsqqd0ee
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRY2JlMnhHdGJYWHAyZzdn
            bnFxQTQ2dUhBUXF1OVBDNld1azRISXFJT1RFCjhybjUxOWo4TllmbUlMbkhsK3RG
            WUtIZkhaWm01TjdWUlpFRzFrS3JTL3MKLS0tIHZGRFFhREZuc2d5ZEZpbDVVMDRL
            cnFyWitJZnRrVHlheG5pVmFibzdwMFUKvbUDZ7j+poKLZ7Gtf/n/L+rrh0BGk7fs
            6RTL3n8MS4aMs9pqHqI1qMOPSGX2yl1pcXC0dToYXP4VStNziHCnqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T08:32:10Z"
    mac: ENC[AES256_GCM,data:3O1/+DTCOQhwy40gsEzawf2i2cQlsC79/pl+HkXO8vfVSy3ZNmceVfPVPtRIrZb+ybJVMx0inGD7Qt8I7k7CMVdLKkZR0AQZ6ipLv+hZnnIxRMftOMaA57apQjYhsvdgRRmVY68GCre7mgBZNSJNbvUzw9oOHSzqGIiibH4OI24=,iv:IgANI4HV/DVtudfjrs8KGZlT1Oj104k0ouAuGGF4EpA=,tag:Q/M2R9I2ztvgWVmCm1+Csw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
