apiVersion: v1
kind: Secret
metadata:
    name: pdns-secrets
    namespace: network-infra-ams23
data:
    PDNS_AUTH_API_KEY: ""
sops:
    age:
        - recipient: age13qg6tpdjfjxcucc9v0lprl2q8wfzvstamh6a6zhnmedq835f3ehsc56thu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ1orbHlSejM3TCt5cFlh
            R3QrbEdMeVhpN2RzdTZyMlQ3WTZ2Rk1paUVBCjY0YWdUSysreTRnckd0c1gvMWYv
            eUFoYW4xUEZVVW1QVW5IeHZZQ2F5ZFUKLS0tIDlRTkV2SGg2NWZZVzJieGwwSW5N
            QythVjFXOVB6UlNBakcxOVFPSVo1QTQKa1nFv/zTnsZgTL9icOEZUSXY/ttJEN/X
            jRkq1tQdk7GmKScGB153IyAqasDat0BGi3a72I+O+yfoRqE6Ba+6Qw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f8vgexpv2fs0yhjes9tqn0rum4j7l0lxupxk66nn7jpa6cyh3etsqqd0ee
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTG1xbmtmVWs1UmJhNHZk
            U01mUHUzbkM5U3JZS05UM3dEeDQ0RFlnOGg0CldsRC9oRXlkUVVEOUNXUktIdW9I
            UzFub29jcCtML2NoQ1pkcHZ3WC9Tb1kKLS0tIGpjczlQT0xaUmVXSG10V0p5Q2Vs
            ODN0MlNVVStzK00rc1hCYlhDdWVDNVkKWiGvYvs7LtxmHWlE6R7Sx0rckTY8zvlT
            s/zRr8Ine8AMCYSjgJF/noZPRzEwB/z8yQUgPt1m5BVAJCxcffs+vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T08:24:37Z"
    mac: ENC[AES256_GCM,data:ZVOK+LsUw5FVdsDgoK2ny4hJPdnSgY2lLjkdFStPul84tcs9xcOr06UzICcIU0Q7fSX0BnwJ/ZR/bzifv6xIZWO8r0j1bsnKiEi1/BqzNRRk+P2dkByOi6fcTLXUuoLv3nTeIAic4ni80I0Dei+34jsy0RChmXPjVG/cMr5cVDQ=,iv:R3tqhSkSJSe3tInWVPEM3G+Y+P5vJvZy49fCdUUleao=,tag:mPAnD40ypbjk5jv0jXMQvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
