apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m
  url: oci://quay.io/metallb/chart/metallb
  ref:
    semver: 0.15.3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: metallb
    namespace: flux-system
