apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: dns-gateway
  namespace: kube-system
spec:
  gatewayClassName: eg
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: dns-nodeport
  listeners:
  - allowedRoutes:
      kinds:
      - kind: TCPRoute
    name: dns-tcp
    port: 53
    protocol: TCP
  - allowedRoutes:
      kinds:
      - kind: UDPRoute
    name: dns-udp
    port: 53
    protocol: UDP
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: dns-nodeport
  namespace: kube-system
spec:
  logging:
    level: {}
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
              - name: dns_tcp
                port: 53
                protocol: TCP
                nodePort: 53
              - name: dns_udp
                port: 53
                protocol: UDP
                nodePort: 53
